### ISSUE TITLE
No otmcjnni in Java.labrary.path error

### ISSUE THREAD

**Issue by obanji** [michaelO93/Intranet-based-biometric-solution-for-screening-student-s-record#1]
Please the code is breaking when the fingerprint button is clicked and this is the error it throws can you render any help....
Thanks

**java.lang.UnsatisfiedLinkError: no otmcjni in java.library.path**
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at com.digitalpersona.onetouch.jni.MatchingLibrary.<clinit>(MatchingLibrary.java:16)
	at com.digitalpersona.onetouch.jni.Matcher.<clinit>(Matcher.java:8)
	at com.digitalpersona.onetouch.processing._impl.DPFPEnrollmentFactoryImpl$EnrollmentImpl.<init>(DPFPEnrollmentFactoryImpl.java:40)
	at com.digitalpersona.onetouch.processing._impl.DPFPEnrollmentFactoryImpl.createEnrollment(DPFPEnrollmentFactoryImpl.java:20)
	at unnbiometrics.EnrollmentForm.<init>(EnrollmentForm.java:17)
	at unnbiometrics.addStudentForm.fingerPrintBtnActionPerformed(addStudentForm.java:588)
	at unnbiometrics.addStudentForm.access$600(addStudentForm.java:34)
	at unnbiometrics.addStudentForm$7.actionPerformed(addStudentForm.java:192)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: com.digitalpersona.onetouch.jni.MatchingLibrary.init()V
	at com.digitalpersona.onetouch.jni.MatchingLibrary.init(Native Method)
	at com.digitalpersona.onetouch.jni.MatchingLibrary.<init>(MatchingLibrary.java:36)
	at com.digitalpersona.onetouch.jni.MatchingLibrary.<clinit>(MatchingLibrary.java:20)
	at com.digitalpersona.onetouch.jni.Matcher.<clinit>(Matcher.java:8)
	at com.digitalpersona.onetouch.processing._impl.DPFPEnrollmentFactoryImpl$EnrollmentImpl.<init>(DPFPEnrollmentFactoryImpl.java:40)
	at com.digitalpersona.onetouch.processing._impl.DPFPEnrollmentFactoryImpl.createEnrollment(DPFPEnrollmentFactoryImpl.java:20)
	at unnbiometrics.EnrollmentForm.<init>(EnrollmentForm.java:17)
	at unnbiometrics.addStudentForm.fingerPrintBtnActionPerformed(addStudentForm.java:588)
	at unnbiometrics.addStudentForm.access$600(addStudentForm.java:34)
	at unnbiometrics.addStudentForm$7.actionPerformed(addStudentForm.java:192)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by michaelO93** [comment]
Thanks for reaching out.

Check the fingerprint hardware driver you're using if it's installed
properly in your machine(the environment variables should be set properly).

FYI : Use digitalpersona u.are.u 4000 or 4500.


Regards,

**Comment by michaelO93** [comment]
Addendum : that error 'no octmjnni' indicates that it's not seeing the
fingerprint driver.

**Comment by obanji** [comment]
Thanks bro
But my question is can we use any fingerprint scanner with the software or
is it a specific type of scanner we have to you use? The scanner I'm trying
to use is SecuGen biometric solutions.

**Comment by michaelO93** [comment]
Ehya,  I understand but the sdk I used was specific to digitalpersona , you
can use secugen fingerprint but you have to use the sdk and driver.


On Jan 22, 2017 8:58 PM, "Banji Olorundare" <notifications@github.com>
wrote:

Thanks bro
But my question is can we use any fingerprint scanner with the software or
is it a specific type of scanner we have to you use? The scanner I'm trying
to use is SecuGen biometric solutions.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/michaelO93/Intranet-based-biometric-solution-for-screening-student-s-record/issues/1#issuecomment-274354726>,
or mute the thread

**Comment by obanji** [comment]
Okay thanks

But please how much did you think the digita persona fingerprint scanner
will cost, because the ones I tried checking online are very expensive.

**Comment by michaelO93** [comment]
It should be around 20k as of last year but I used my supervisor's

**Comment by obanji** [comment]
Okay Thanks

**Comment by michaelO93** [comment]
You're welcome.
